#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

cd /var/lib/mautrix-telegram

if [[ ! -e /var/lib/mautrix-telegram/alembic ]]; then
  ln -s /usr/share/mautrix-telegram/alembic ./
fi
if [[ ! -e /var/lib/mautrix-telegram/alembic.ini ]]; then
  ln -s /usr/share/mautrix-telegram/alembic.ini ./
fi
sudo -u mautrix-telegram alembic -x config=/etc/synapse/mautrix-telegram/config.yaml upgrade head
